name: 'Update APT Source'
description: 'A GitHub Action for managing Debian/Ubuntu APT repositories'
author: 'coScene Technologies'

# 定义输入参数
inputs:
  ubuntu-distro:
    description: 'Ubuntu distribution codename (e.g., focal, jammy, or all)'
    required: true
  deb-paths:
    description: 'Paths to .deb packages, separated by newlines'
    required: true
  architectures:
    description: 'Architectures for each .deb package, in the same order as deb-paths'
    required: true
  access-key-id:
    description: 'OSS access key ID'
    required: true
  access-key-secret:
    description: 'OSS access key secret'
    required: true
  gpg-private-key:
    description: 'GPG private key for signing (base64 encoded)'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'package'
  color: 'blue'
