name: 'Update APT Source'
description: 'A GitHub Action for managing Debian/Ubuntu APT repositories'
author: 'coScene Technologies'

inputs:
  ubuntu_distro:
    description: 'Ubuntu distribution codename (e.g., focal, jammy, or all)'
    required: true
  deb_paths:
    description: 'Paths to .deb packages, separated by newlines'
    required: true
  architectures:
    description: 'Architectures for each .deb package, in the same order as deb-paths'
    required: true
  storage_type:
    description: 'Cloud storage type, aws or oss for now'
    required: true
  endpoint:
    description: 'Cloud storage endpoint'
    required: true
  region:
    description: 'Cloud storage region'
    required: true
  bucket_name:
    description: 'Cloud storage bucket name'
    required: true
  access_key_id:
    description: 'Cloud storage access key ID'
    required: true
  access_key_secret:
    description: 'Cloud storage access key secret'
    required: true
  gpg_private_key:
    description: 'GPG private key for signing (base64 encoded)'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'package'
  color: 'green'
